### ISSUE TITLE
“Outstanding expertises” notification includes descriptionless expertises

### ISSUE THREAD

**Issue by Wilto** [bocoup/bots#100]
I blanked on the fact that you can’t update expertises without descriptions, so this reminder kinda threw me off:

![image](https://cloud.githubusercontent.com/assets/439942/13577529/de80d878-e460-11e5-9150-a9b88e66b3b6.png)

We might want to exclude descriptionless expertises from these reminders.

**Comment by tkellen** [comment]
this was resolved in https://github.com/bocoup/bots/commit/68cf07029083b6dddbc530fe6f3a38bce40c5bde
