### ISSUE TITLE
Commands should not be case sensitive

### ISSUE THREAD

**Issue by gnarf** [bocoup/bots#104]
![screenshot_20160309-161023](https://cloud.githubusercontent.com/assets/549355/13650649/ac35d596-e611-11e5-936b-6ba87bb1016c.png)

Annoying mobile experience to have to uncap the first letter of every command

**Comment by gnarf** [comment]
Note: this works in Ben's menus... 'Exit' is good enough

**Comment by tkellen** [comment]
@gnarf any chance you'd be willing to PR this? Getting set up with a dev environment is pretty dang quick: https://github.com/bocoup/bots/wiki/Local-Development
