### ISSUE TITLE
Show Previous Value in `expertise update _____`

### ISSUE THREAD

**Issue by gnarf** [bocoup/bots#109]
Went to update my RWD experience, but I couldn't tell what it was set at before, we should probably tell the user "You currently have selected 4 / 2 for this expertise" type of message.

**Comment by cowboy** [comment]
How about, instead, this: https://github.com/bocoup/bots/issues/110

**Comment by cowboy** [comment]
My idea was that I don't want it to tell you what you currently have because it might bias your response. That said, if you DO say the same thing again, maybe it shouldn't ask you for a reason.

**Comment by tkellen** [comment]
Closing here but we can address this over at bocoup/skillsbot if we determine it's still desirable.
