### ISSUE TITLE
thanksbot gets confused when slack attaches urls

### ISSUE THREAD

**Issue by kadamwhite** [bocoup/bots#11]
![image](https://cloud.githubusercontent.com/assets/442115/12303843/9c371d3c-b9fa-11e5-8add-be22297af3a9.png)

my guess is that when slack appends a link from the convo you're having, it treats it like an edit, which causes thanksbot to raise an error. There's a minor chance that this is a result of the markdown formatting (`*mind blown*`), but my assumption is that the URL attachment's the culprit.

@tkellen has confirmed that the DB is updated appropriately with the original message.

Suppressing the message in this cases may be a sufficient fix.

**Comment by tkellen** [comment]
Closing as wontfix. Thanksbot has been retired.
