### ISSUE TITLE
support command `pombot start`

### ISSUE THREAD

**Issue by tkellen** [bocoup/bots#119]
When the user says `pombot start` in the same channel as pombot, do the following:

**Pom IS NOT RUNNING**
> @here, pom started! You have 25 minutes, happy pomming!

-  **...20 minutes later**
> @here, you have 5 minutes left in the pom.

-  **...25 minutes later**
>  @here, times up! The pom is over. Take a 5 minute break!

-  **...5 minutes later**
> @here, your five minute break is over! Would you like to start another pom?

**Pom IS RUNNING**
> There is already a pom running, there are X minutes left.

**Pom IS ON BREAK:**
> We are in the middle of a break, there are X minutes left.

**Comment by jennschiffer** [comment]
resolved in #125
