### ISSUE TITLE
🍅bot:  @ message pommers with messages during a pom

### ISSUE THREAD

**Issue by iamjessklein** [bocoup/bots#143]
After a pom has been started, it would be really great if users were alerted by name about messages. This will help users to get notified with reminders about 5 mins left in the pom and when the pom concludes.

Example: 

_Pam and Jess declare that they will do a pom:_
<img width="542" alt="screen shot 2016-06-07 at 2 11 17 pm" src="https://cloud.githubusercontent.com/assets/535012/15869306/d8c4bca0-2cb9-11e6-859a-dc7b3511881b.png">

_Jess starts the pom_
<img width="421" alt="screen shot 2016-06-07 at 2 11 48 pm" src="https://cloud.githubusercontent.com/assets/535012/15869324/f3ab9c5a-2cb9-11e6-81bf-bf170594e983.png">

^ this message **should** say "....@ jess and @ pam have 25 minutes left!"

_All participants are warned that they have 5 mins left in the pom_
<img width="435" alt="screen shot 2016-06-07 at 2 11 58 pm" src="https://cloud.githubusercontent.com/assets/535012/15869363/21e3264c-2cba-11e6-958f-712a2831c58a.png">

^ this message **should** say ".... @ jess and @ pam have 5 minutes..." 

 _All participants are notified that the pom has ended._ 
<img width="460" alt="screen shot 2016-06-07 at 2 12 03 pm" src="https://cloud.githubusercontent.com/assets/535012/15869411/50e7ee46-2cba-11e6-80a4-129236f63e4f.png">

^ this message **should** say " .... @ jess @ pam : your 🍅 is complete

cc/ @jennschiffer @cowboy @tkellen

**Comment by jennschiffer** [comment]
would it be okay to have the @ replies at the end of the message, that way the important info is in the beginning and readable if there were like 1000 names after?

**Comment by cowboy** [comment]
The bot could also individually DM people status messages, instead of posting them in the channel. Or both.

**Comment by iamjessklein** [comment]
Since we are promoting [openness](https://openmatt.org/2011/04/06/how-to-work-open/) (with the process)  I think that it should @ reply at the end of the message. +1 @jennschiffer

**Comment by jennschiffer** [comment]
i'd prefer keeping in the channel where the pom is running. that way we know what pom the warning is for - in case a user is running multiple poms in different channels

**Comment by cowboy** [comment]
What if the bot messaged each user in a DM with the reason they specified? Then instead of a general:

> **Pombot** warning - you have 5 minutes left in this pom @cowboy @jennschiffer @iamjessklein 

We each might see an individual message in DM like:

> **Pombot** Warning - you have 5 minutes left to add logged out views into the deck for tomorrow

Or:

> **Pombot** Warning - you have 5 minutes left to do something something

It could also still message the channel with a general warning, like it does now.

Also, is it likely that people will participate in multiple simultaneous timers?

**Comment by iamjessklein** [comment]
🕓 that multiple timers question is interesting. I think that it's safe to assume that if they are publicly pomming they will be doing it together.
