### ISSUE TITLE
`expertise update` fail: robocoup probably thinks I don't exist

### ISSUE THREAD

**Issue by lyzadanger** [bocoup/bots#145]
After what (I presume is) the last step of the update for a skill:

```
An error occurred: `INSERT INTO employee_expertise (
 employee_id,
 expertise_id,
 experience_rating,
 interest_rating,
 notes
) VALUES (
 (SELECT id FROM employee WHERE slack=$1),
 $2,
 $3,
 $4,
 $5
)
- null value in column "employee_id" violates not-null constraint`
```

Background:

* This is the first entry I've tried to make
* If it matters (I doubt it), the skill I was adding was WordPress

**Comment by cowboy** [comment]
I'd imagine this isn't working because your slackname is `lyzadanger` but the value in the database is `lyza`. @tkellen, can you confirm?

**Comment by tkellen** [comment]
Indeed it is. I've fixed this over at http://db.bocoup.com. Thanks for the sanity check @cowboy.
