### ISSUE TITLE
utilization - handle employees that started after the beginning of the year / within the last six months

### ISSUE THREAD

**Issue by pbeshai** [bocoup/bots#154]
The current representation shows time as `Unscheduled` for time when you were not yet at Bocoup. This has the side-effect is that the percentages for everything else are artificially low. It would be good if start date was taken into consideration when computing percentages. I think this applies to both the **2016 to date** and **Last Six Months** sections.

For example,

```
My Utilization Status: 2016 to Date*​
>`███████     68%` Unscheduled (​*86 days*​)
> `██          18%` Billable (​*23 days*​)
...
```

**Comment by tkellen** [comment]
closing as wontfix, this feature has been retired in #189
