### ISSUE TITLE
category is being split in the same date range

### ISSUE THREAD

**Issue by leobalter** [bocoup/bots#155]
Running my utilization today I've noticed the `2016 to Date` list split the Consulting category in 2 parts.

```
​*My Utilization Status: 2016 to Date*​
>`████████    81%` Billable (​*104 days*​)
>╰ `████████    80%` Consulting (​*103 days*​)
>╰ `▌            1%` Consulting (​*1 day*​)
```

I have no clue what cause this but I can tell I've only worked in the same contract this year (test262)

The `Last Six Months` list shows it correctly, featuring one extra billable day (from 2015) and it does not split consulting.

```
​*My Utilization Status: Last Six Months*​
>`████████    80%` Billable (​*105 days*​)
>╰ `████████    80%` Consulting (​*105 days*​)
```

**Comment by tkellen** [comment]
This is an off-by-one with regards to past and future utilizations. I'll take a look at it after I resolve #154. Might be a bit--I'm doing most of this work early in the morning before people roll in.

**Comment by leobalter** [comment]
Thanks! This is not urgent or blocking anything, it's still easy to read my utilization, just weird.

**Comment by tkellen** [comment]
Closing, this is no longer relevant following the landing of #189
