### ISSUE TITLE
My Utilization Status: current year

### ISSUE THREAD

**Issue by leobalter** [bocoup/bots#157]
Can we have a utilization summary for the current year? I would like to see utilization status with the sum for 2016.

**Comment by tkellen** [comment]
@leobalter Is that not covered by the "My Utilization Status: 2016 to Date" section?

**Comment by leobalter** [comment]
I'm sorry for the super long delay, I missed some notifications.

Our goal is 80% utilized on billable b2b projects, I want to know how I am scheduled for the year.

Example: I have 109 days billable from a total of 266 week days in 2016. This means I've already  got 40.98% of billable days in 2016.

Most important: I want to check how many specific non-billable days I have available, considering I want to use some with vacations. This is more helpful than foreseeing the next six months.

So I can tell my uses so far for 2016 (to Date + upcoming months):

- Non-Billable: 60 days (**22.56%**)
- Pro-dev: 14 days (**5.27%**)
- Perch: 17 days (*6.39*%**)
- PTO: 17 days (**6.39%**)
- Holiday: 8 days (**3%**)
- Internal Event: 3 days (**1.13%**)
- Sick Time: 1 day (**0.38%**)

I excluded the Needs Attention to this list as this is uncertain.

This manual summary tells me a lot of useful information. I've requested a PTO (+8 days in 2016) for the end of the year based on my own calculations before I've got this data above.

There I suggested I could work on some holidays to fit these weeks, now it makes more sense maybe I will have to do it for sure.

This is also good information to let me know what I could use for upcoming TC39 meetings, which I honestly want to prioritize my requested PTOs right now.

**Comment by leobalter** [comment]
extra simulation, in case I get my PTO request approved with 2 holidays out (working):

- Non-Billable: 66 days (**24.81%**)
- Pro-dev: 14 days (**5.27%**)
- Perch: 17 days (**6.39%**)
- PTO: 25 days (**9.40%**)
- Holiday: 6 days (**2.26%**)
- Internal Event: 3 days (**1.13%**)
- Sick Time: 1 day (**0.38%**)

**Comment by tkellen** [comment]
closing as wontfix, this functionality has been retired.
