### ISSUE TITLE
Add "undo" command to thanksbot

### ISSUE THREAD

**Issue by cowboy** [bocoup/bots#169]
- It could undo the last thing you said to it, as long as that thing hasn't already been said in the weekly email. This would allow you to undo multiple things.
- It would echo what it was removing back to you, so that you'd be reminded what, exactly, was being removed.

Because:

![](http://i.imgur.com/5MPKtG9.png)

**Comment by tkellen** [comment]
PRS welcome!

**Comment by iamjessklein** [comment]
+1 to this suggestion.

**Comment by tkellen** [comment]
Closing as wontfix. Thanksbot has been retired.
