### ISSUE TITLE
thanksbot: ignore messages that aren't actual "thanks" messages

### ISSUE THREAD

**Issue by cowboy** [bocoup/bots#170]
We can probably use some super basic heuristics to determine which messages aren't actual "thanks" messages, and display a helpful message to that effect instead of recording the message.

For example, if the message only contains one or two words, it's probably not a thanks message, but instead an accidental message meant for another bot. Can the bot require a minimum number of words? If the message isn't long enough, the bot can easily ask the user to wax poetic and embellish their message!

Thoughts?

**Comment by tkellen** [comment]
Closing as wontfix. Thanksbot has been retired.
