### ISSUE TITLE
SQL error in utilization report

### ISSUE THREAD

**Issue by bmac** [bocoup/bots#180]
#### Expected
running `/dm robocoup utilization` should print a utilization report.

#### Actual
running `/dm robocoup utilization` prints out the [utilization_metric.sql](https://github.com/bocoup/bots/blob/eb1cc6adf30daf7ff59f5a14cf15eab061b9af5c/src/db/utilization_metric.sql) with an error that "column ph.is_billable does not exist".

**Comment by tkellen** [comment]
Thanks @bmac! I need to put a pending notification in for this report. As Jory mentioned in our companywide year plan, we're moving to a revenue based model rather than a percentage-utilized model and these queries need to be updated. I'll address this before EOD.

**Comment by tkellen** [comment]
This is linked to:
https://github.com/bocoup/api/pull/394

**Comment by tkellen** [comment]
I've updated my original comment to link to the year plan. Also, for posterity, here is the relevant section discussing this:

> One of the things we learned in 2016 is that targeting an average utilization rate of 80% across the board is “putting the emphasis on the wrong syllable.” This year’s financial plan therefore does not set a target utilization rate for the whole company. Instead, we’re focusing on hitting an average annualized Revenue/Direct Staff of $230k. This approach better reflects the impact of different types of services we have at Bocoup on project success, particularly in our newer capabilities like Design, Project Management and Continued Access.

**Comment by tkellen** [comment]
closing as wontfix, this functionality has been removed.
