### ISSUE TITLE
Bot Idea: Community Bot (via @gnarf)

### ISSUE THREAD

**Issue by iros** [bocoup/bots#23]
This is entirely @gnarf's idea that came up during our conversation but it was SO great that I just wanted to throw it in as a request before it leaves my mind.

We all love ThanksBot, it is the best email to get in the morning!

It would be equally awesome to have a new bot called **CommunityBot** to whom we can message the many awesome open source, community development etc activities that we do. Then, it could send out yet another awesome email aggregating all of those activities and thus know about the cool things our teammates get to do. Did you make an OS commit or PR? Did you organize a meetup? Did you write a blog post? Did you speak at a conference? Do share!

Thanks @gnarf for this awesome idea. @tkellen and I love it!

Also ping @jugglinmike.

Also :banana:

**Comment by tkellen** [comment]
We're in a place now where this would be super trivial to implement. If someone wants to do it, just ping me and I'd be happy to provide guidance!
