### ISSUE TITLE
Badgebot: Identify the badge objects

### ISSUE THREAD

**Issue by iamjessklein** [bocoup/bots#42]
As per the [open badge specification](http://openbadgespec.org/examples/), every badge should have an assertion, issuer and badge class. Let's use this issue to figure out what that info should be.

**Comment by iamjessklein** [comment]
I think this is the issuer metadata:

```
{
  "@context": "https://w3id.org/openbadges/v1",
  "type": "Issuer",
  "id": "https://bocoup.com/organization.json",
  "name": "Bocoup",
  "image": "https://static.bocoup.com/assets/img/bocoup.png",
  "url": "https://bocoup.com/",
  "email": "badges@bocoup.com",
  "revocationList": "https://bocoup.com/revoked.json"
}
```

**Comment by iamjessklein** [comment]
.... and I think this is the assertion metadata

```
{
  "@context": "https://w3id.org/openbadges/v1",
  "type": "Assertion",
  "id": "https://bocoup.com/mentor-badge.json",
  "uid": "f2c20",
  "recipient": {
    "type": "email",
    "hashed": true,
    "peer"
    "identity": "sha256$c7ef86405ba71b85acd8e2e95166c4b111448089f2e1599f42fe1bba46e865c5"
  },
  "image": "https://bocoup.com/badges/mentor-badge.png",
  "evidence": "https://github.com/bocoup/bots/wiki/Badgebot",
  "issuedOn": 1359217910,
  "expires": 1609458300,
  "badge": "https://bocoup.com/badges/mentor-badge.json",
  "verify": {
    "type": "hosted",
    "url": "https://bocoup.com/badges/brendan-mentor-badge.json"
  }
}
```

**Comment by kayaelle** [comment]
For the issuer metadata, the id should be the url where this data .json file is hosted. This is the same url you'll use in the badge class for issuer.

For the assertion metadata the id should be the url where the assertion metadata is hosted. This data will be unique per earner so the url will be unique. This is the same url you would use for the verify url.

You can generate these files dynamically like https://bocoup.com/mentor-badge-award/<award id> or host static .json files. 

Also something to consider re: issuer - the issuer may be Bocoup but the person who is giving the badge may be more important to the earner. Right now the spec doesn't accommodate having more than one issuer per badge . You can extend the Badge Class by adding the Original Creator extension where the original creator .json is Bocoup and the issuer is the person who awarded the badge.

**Comment by iamjessklein** [comment]
Thanks @kayaelle for all of those clarifications. I didn't realize that there was a single - issuer restriction. This is an interesting problem considering that these are peer badges.

**Comment by tkellen** [comment]
closing as wontfix,
