### ISSUE TITLE
Robocoop Perch shown in days instead of weeks

### ISSUE THREAD

**Issue by deathbearbrown** [bocoup/bots#50]
When I type `perch` at robocoop now I get back:

_Perch Status as of February 5th, 2016_​

> You have used ​_0.20_​ of ​_4.00_​ planned perch weeks this year.
> The company average for billable team members is ​_0.87_​ verified perch weeks this year.
> We are ​_over_​ our company-wide planned perch by ​_16.30_​ verified perch weeks this year.
> ​_1_​ out of ​_18_​ billable team members have had 4+ verified perch weeks this year.
> You ​_are_​ currently coded as a billable team member. Please email hr@bocoup.com if this needs to be updated.

The .20 of 4.00 weeks is a little weird. It might be more readable to have that in days.

eg.

> You have used ​1 day​ of ​20 days (4 weeks)​ planned perch this year.

OR

> You have used 5% (1 day) of your 4 weeks planned perch this year.

**Comment by brianloveswords** [comment]
I like the second option!

**Comment by jennschiffer** [comment]
i second the second option!

**Comment by bobholt** [comment]
I like either of those!

**Comment by tkellen** [comment]
This functionality has been removed, giving this a close.
