### ISSUE TITLE
Pipeline Bot shows no data

### ISSUE THREAD

**Issue by JasminRuth** [bocoup/bots#54]
robocoupBOT [10:10 AM] 
>​*Sales Pipeline Status as of 12AM on February 15th, 2016*​
> The weighted value of our sales pipeline is currently ​*$0*​.
> We are at ​*0%*​ of our ongoing goal of ​*$2,500,000*​ for ​*Q1*​ of ​*2016*​.

**Comment by tkellen** [comment]
Thanks for the heads up Jasmin! Looks like the daily deal sync needs to be confirmed working (that's what powers this data). I will check first thing tomorrow AM.

**Comment by tkellen** [comment]
(Pipedrive's API semi-frequently goes down for short periods and I need to build retry-logic into the deal sync)

**Comment by tkellen** [comment]
resolved! this will never happen again.
