### ISSUE TITLE
add expertise update

### ISSUE THREAD

**Issue by tkellen** [bocoup/bots#59]
Sample flow below. Feedback welcome!

> expertise update

Welcome to the expertise updater! Please choose the types of expertise you'd like to update.

**0.** Missing (10)
**1.** All (114) (if this is chosen, the system should proceed through each of the choices below one by one)
**2.** API Frameworks (6 items)
**3.** Content Management Systems (1 item)
**4.** Database Systems (6 items)
**5.** Data Visualization (18 items)
**6.** Deployment & Infrastructure (9 items)
**7.** Design (9 items)
**8.** Education (7 items)
**9.** Javascript App Frameworks/Libraries (5 items)
**10.** Programming Languages (16 items)
**11.** Project Management (7 items)
**12.** Software Engineering (13 items)
**13.** Software Testing (4 items)
**14.** Web Connected Devices (6 items)
**15.** Web Fundamentals (7 items)

> 2

Let's update your expertises in the area of **API Frameworks**.

Please choose the expertise you'd like to update:

**1.** All (6) (if this is chosen, the system should proceed through each of the choices below one by one)
**2.** Django (no data)
**3.** Endpoints (experience=3 interest=2)
**4.** Express (experience=3 interest=2)
**5.** Flask (experience=3 interest=2)
**6.** Ruby on Rails (experience=1 interest=3)
**7.** Sinatra (experience=2 interest=1)

> 2

Let's update your expertise for the **technology** **Django**.

Django description here.

Please choose your experience level:

**1.** I have no experience with this.
**2.** I have some experience but I am not yet confident with this.
**3.** I have some experience and feel confident with this.
**4.** I have lots of experience and can teach others this.
**5.** I have lots of experience and can lead mission critical work on this front.

> 3

Let's update your interest for the **technology** **Django**.

Django description here.

Please choose your interest level:

**1.** I am not sure what this is.
**2.** I have no interest in this.
**3.** I have mild interest in this.
**4.** I have a deep interest in this.
**5.** Words cannot express how much I enjoy this.

> 3

---

*Only show this screen if there is existing data. We will blank everyone out when we launch the new scale.*

Let's leave a note about why your experience and interest is changing for the **technology** **Django**.

> Because I said so.

---

Okay! We are going to update your expertise data about the **technology** **Django** to reflect the following:

**I have some experience and feel confident with this. (3)**
**I have mild interest in this. (3)**

---

*Only show this section if there is existing data. We will blank everyone out when we launch the new scale.*

The last time you updated this was on **date** and you had said:

**I have some experience but I am not yet confident with this. (2)**
**I have mild interest in this. (3)**

We are changing this for the following reason:

**Because I said so**.

---

Is that okay?

1. Yes
2. Start over

> 1

**Comment by tkellen** [comment]
PS: I can add the textual representations of the scale to the db so we don't have to hard code them.

**Comment by cowboy** [comment]
Closing for now. Once #60 and #62 are done, this can be implemented (if still desired) via #63.
