### ISSUE TITLE
add expertise update missing dialog

### ISSUE THREAD

**Issue by tkellen** [bocoup/bots#60]
Sample flow below. Feedback welcome!

> expertise update missing

Welcome to the expertise updater! You have no data for **#** expertises. Please choose which you'd like to update:

1. All (3)
2. Blacksmithing
3. Woodworking
4. General Construction

> 2

(follow flow from #59)

If the team member is not missing any expertise entries, the system should just say so and abort.

**Comment by tkellen** [comment]
closed in favor of #59

**Comment by cowboy** [comment]
Reopening, will implement for now, without the menu component.

### Flow

> expertise update missing

You have no data for the following 3 expertises: **Basic Electronics, Ruby, Yak Shaving**

Let's update your expertise for **Basic Electronics**.

Basic Electronics description here.

Please choose your interest level for **Basic Electronics**, or type ​**exit**​ to cancel. You have 30 seconds:

**1.** interest choice text tbd
**2.** interest choice text tbd
**3.** interest choice text tbd
**4.** interest choice text tbd
**5.** interest choice text tbd

> 4

Please choose your experience level for **Basic Electronics**, or type ​**exit**​ to cancel. You have 30 seconds:

**1.** experience choice text tbd
**2.** experience choice text tbd
**3.** experience choice text tbd
**4.** experience choice text tbd
**5.** experience choice text tbd

> 2

I will update your expertise data about the technology **Basic Electronics** to reflect the following:

**Interest = 4 (interest choice text tbd)**
**Experience = 2 (experience choice text tbd)**

Is this ok? Please make a choice, or type ​**exit**​ to cancel. You have 30 seconds:

**1.** Yes.
**2.** No, re-choose interest and experience for **Basic Electronics**.

> 1

**Done! Interest set to 4. Experience set to 2.**

You have no data for the following 2 expertises: **Ruby, Yak Shaving**

Let's update your expertise for **Ruby**.

Ruby description here.

...many questions answered...

You have no missing expertise data. View your expertise list with `expertise me`.

**Comment by cowboy** [comment]
@tkellen how do you feel about this updated flow?

**Comment by tkellen** [comment]
:+1:
