### ISSUE TITLE
switch to pg-promise

### ISSUE THREAD

**Issue by tkellen** [bocoup/bots#66]
it does everything we need and it does it better than our current abstractions:
https://www.npmjs.com/package/pg-promise
https://github.com/vitaly-t/pg-promise#query-files

**Comment by vitaly-t** [comment]
[pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) can be a helpful example of how to organize your database layer ;)

**Comment by tkellen** [comment]
Closing as wontfix.
