### ISSUE TITLE
Strange behavior when entering unexpected input in expertise update

### ISSUE THREAD

**Issue by bobholt** [bocoup/bots#75]
> Robocoup BOT 4:29 PM: ​You selected ​3​ for experience, thanks!​You've entered the following for ​MySQL​. Is this ok?
  - Interest: ​I have no feelings for or against this.​ (3)
  - Experience: ​I have some experience and feel confident with this. (3)
  - [​1​] Save these changes.
  - [​2​] No, re-choose interest and experience for ​MySQL​.​You have 60 seconds to answer. Type ​exit​ to cancel.​

bobholt 4:29 PM: `

> Robocoup BOT 4:29 PM: ​Sorry, but ``` is not a valid response. Please try again.​You've entered the following for ​MySQL​. Is this ok?
  - Interest: ​I have no feelings for or against this.​ (3)
  - Experience: ​I have some experience and feel confident with this. (3)
  - [​1​] null
  - [​2​] Save these changes.
  - [​3​] No, re-choose interest and experience for ​MySQL​.​You have 60 seconds to answer. Type ​exit​ to cancel.​

bobholt 4:29 PM: 1

> Robocoup BOT 4:29 PM: Expertise for ​MySQL​ updated: Interest set to 3. Experience set to 3.
```

**Comment by cowboy** [comment]
Closed via 0a98ad2314c09136f47fe8ae0ff25125c93a8158.
