### ISSUE TITLE
Do not enumerate all to-do skills during `expertise update missing`

### ISSUE THREAD

**Issue by kadamwhite** [bocoup/bots#76]
![image](https://cloud.githubusercontent.com/assets/442115/13363570/0d76217c-dc98-11e5-9425-dcd77f7b8221.png)
That huge block of text gets spit out on each iteration through the tool: this is a lot of added visual noise that we probably don't need, I'd vote to change it to "Adding missing data for 81 expertises..." or something more summary and terse. If we're using `update missing` then we're just stepping through skills, so the list of what's there isn't especially useful.

**Comment by cowboy** [comment]
Here are a few options. Thoughts?

1) Show the number remaining, along with a preview of the first few (right now, limited to 5) and a summary of how many more:

![](https://i.gyazo.com/0b908a045851b284ec54e617c867ea82.png)

2) Just show the number remaining, with no preview:

![](https://i.gyazo.com/c8f539776e1d8d539e2512da92ebee0f.png)

**Comment by cowboy** [comment]
It could also show the big list once, initially. Or, some combination of all these things.

Basically, the bot can:

* show some text when it initially responds to `expertise update missing`, but not again.
* show some text before every question, individually.

**Comment by cowboy** [comment]
This is what I have right now, and I like it:

`expertise update missing` with one missing:

> You have no data for 1 expertise. Let's update it:

`expertise update missing` with three missing:

> You have no data for 3 expertises. Let's update the first:
> You now have no data for 2 expertises. Let's update the next:
> You now have no data for 1 expertise. Let's update it:

@tkellen, thoughts?

**Comment by tkellen** [comment]
Seems sensible to me!

**Comment by kadamwhite** [comment]
I'd vote for (2), with no preview. Rather than enumerating "the first", etc, I did like the way you had it in the screenshot where it said, "you have X, let's update Y" -- but I don't have strong feelings about it.
