### ISSUE TITLE
expertise descriptions are incomplete

### ISSUE THREAD

**Issue by vlandham** [bocoup/bots#94]
<img width="425" alt="screen shot 2016-03-04 at 9 42 50 am" src="https://cloud.githubusercontent.com/assets/9369/13535303/51ffc6bc-e1ee-11e5-9e13-f586563f3459.png">

If we are capable of indicating "​I have no experience with this." then by definition the thing itself cannot be "self explanatory"

**Comment by tkellen** [comment]
Your point is well taken. I'll be sure these get fixed:
```sql
bocoup=> select id,name from expertise where description='Self explanatory.';
 id  |              name
-----+---------------------------------
 104 | Writing Educational Material
 107 | Client Communication
 108 | Code Reviews
 110 | Work Prioritization
 111 | Work Scoping
  68 | Writing Technical Documentation
(6 rows)
```

**Comment by tkellen** [comment]
I've removed the descriptions for these expertises so they drop off our system until they've been properly described (which will happen soon).
