### ISSUE TITLE
Improve output for expertise and interest ratings

### ISSUE THREAD

**Issue by iros** [bocoup/bots#97]
Current output is a bit rough to read:

![image](https://cloud.githubusercontent.com/assets/18690/13543041/91521440-e235-11e5-8c83-1eebdc666fd6.png)

What if instead, we used some fancy characters and created something like this:

```
Experience    | Interest
░░░░░░████ (2)| ████████░░ (4)   Data Visualization
░░░░░░░░██ (1)| ██████░░░░ (3)   User Research
```

In this example:
1. Experience and Interest only appear once, as headers
2. Small charts use the darker color to indicate "more-ness"
3. I used 2 boxes for each unit (aka, 10 chars for a value of 1-5) to better align with the headers at the top but that's not a requirement if we need space.
4. We output one skill per row
5. We can sort the list by the sum total of the two scores, OR the interest OR the experience (possibly a user parameter?)

Happy to PR it if folks think this is fun!
pinging @tkellen and @cowboy for their Opinions

**Comment by tkellen** [comment]
I love this idea. The current implementation is the barest of bones simply
exposing the data so we can see it. Please PR away. If you have any trouble
getting the repo rolling, let me know!

Current output is a bit rough to read:

[image: image]
<https://cloud.githubusercontent.com/assets/18690/13543041/91521440-e235-11e5-8c83-1eebdc666fd6.png>

What if instead, we used some fancy characters and created something like
this:

Experience    | Interest
░░░░░░████ (2)| ████████░░ (4)   Data Visualization
░░░░░░░░██ (1)| ██████░░░░ (3)   User Research

In this example:
1. Experience and Interest only appear once, as headers
2. Small charts use the darker color to indicate "more-ness"
3. I used 2 boxes for each unit (aka, 10 chars for a value of 1-5) to
better align with the headers at the top but that's not a requirement if we
need space.
4. We output one skill per row
5. We can sort the list by the sum total of the two scores, OR the interest
OR the experience (possibly a user parameter?)

Happy to PR it if folks think this is fun!
pinging @tkellen <https://github.com/tkellen> and @cowboy
<https://github.com/cowboy> for their Opinions

—
Reply to this email directly or view it on GitHub
<https://github.com/bocoup/bots/issues/97>.

**Comment by tkellen** [comment]
this was resolved in https://github.com/bocoup/bots/pull/101, thanks @iros!
